# This is a basic workflow to help you get started with Actions

name: backend

# Controls when the action will run. 
on:
  push:
    paths:
      -"backend/**"
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Node Version 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - name : npm install and build and deploy
        run: |
          cd backend
          npm cache clean --force
          npm install
          npm install typescript
          npm install express
          npm install -g firebase-tools
          firebase login --interactive
          echo Y | firebase init hosting
          firebase deploy

