# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Daily Stock Details Work Flow
on:
  schedule:
    - cron: "30 15 * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Daily Stock Scrape
      run: |
        python dailystock.py
    - name: Setup Github Config
      run: |
        git config --global user.name "saikr789"
        git config --global user.email "saikrishna.nama@msitprogram.net"
    - name: Commiting New Files
      run: |
        git pull origin master
        git add Data/Stock
        git commit -m "dailystock"
        git push origin master
