name: Feature Creation Kaggle Work Flow
on:
  schedule:
    - cron: "30 16 * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Feature Creation
      run: |
       python kaggle.py
