# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Stock Scrape Work Flow
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Stock Scrape
      run: |
        python previousdaystockdetails.py
    - name: Setup Github Config
      run: |
        git config user.name "saikr789"
        git config user.email "saikrishna.nama@msitprogram.net"
    - name: Commiting New Files
      run: |
        git pull origin master
        git add Data/Stock
        git commit -m "previousdaystockdetails.py"
        git push origin master
